### ISSUE TITLE
Doesn't work for DataGrip 2018.1

### ISSUE THREAD

**Issue by aseredenko** [yseasony/idea-sql-generator-tool#19]
After installing plugin and restarting DataGrip I see this error message

![2018-06-17 19 45 21](https://user-images.githubusercontent.com/6630181/41510095-1a4f4074-7267-11e8-825f-c15eb2625f7c.png)

**Comment by Gohloum** [comment]
I confirm the above.  However here are the details that may be handy:

update failed for AnAction(org.yseasony.sqlgenerator.SqlGeneratorAction) with ID=sqlGenerate: com.intellij.database.view.DatabaseView.getTreeBuilder()Lcom/intellij/ide/util/treeView/AbstractTreeBuilder;
java.lang.NoSuchMethodError: com.intellij.database.view.DatabaseView.getTreeBuilder()Lcom/intellij/ide/util/treeView/AbstractTreeBuilder;
	at org.yseasony.sqlgenerator.SqlGeneratorAction.update(SqlGeneratorAction.java:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:259)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:110)
	at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:91)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:52)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6545)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:423)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.o(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Gohloum** [comment]
And this:

update failed for AnAction(org.yseasony.sqlgenerator.SqlGeneratorAction) with ID=sqlGenerate: com.intellij.database.view.DatabaseView.getTreeBuilder()Lcom/intellij/ide/util/treeView/AbstractTreeBuilder;

**Comment by yseasony** [comment]
Please use the latest version
https://github.com/yseasony/idea-sql-generator-tool/releases

**Comment by aseredenko** [comment]
@yseasony I've tried this one as well, same result.

**Comment by yseasony** [comment]
try v2.2.0

**Comment by fuergaosi233** [comment]
I use v2.2.0 in  DataGrip, no error message.
But nothing happened whether I click on insert or other options.
![image](https://user-images.githubusercontent.com/22197568/54665949-74fa2580-4b23-11e9-9bb6-6eca61b5c3ae.png)

**Comment by yseasony** [comment]
> I use v2.2.0 in DataGrip, no error message.
> But nothing happened whether I click on insert or other options.
> ![image](https://user-images.githubusercontent.com/22197568/54665949-74fa2580-4b23-11e9-9bb6-6eca61b5c3ae.png)
@fuergaosi233  SQL in your clipboard, and paste

**Comment by fuergaosi233** [comment]
sorry,I misunderstood the role of this tool.
