### ISSUE TITLE
PluginException: org.yseasony.sqlgenerator.action.SqlGeneratorAction

### ISSUE THREAD

**Issue by lackovic** [yseasony/idea-sql-generator-tool#26]
Using **IntelliJ IDEA 2022.2.3** running in **Ubuntu 22.04.1 LTS** in **Windows 11 22H2** WSL, I get the following error when opening any project with the IDE:
```
com.intellij.diagnostic.PluginException: org.yseasony.sqlgenerator.action.SqlGeneratorAction (sqlGenerate): group with id "DatabaseViewPopupMenu" isn't registered; action will be added to the "Other" group (module=PluginDescriptor(name=Sql Generator, id=org.yseasony.sqlgenerator, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.2/idea-sql-generator-tool-2.2.1.jar, version=2.2.1, package=null, isBundled=false))
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:356)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getParentGroup(ActionManagerImpl.java:969)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.java:918)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:665)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:167)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:139)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:29)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.lambda$prepareToShow$1(WelcomeFrame.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by yseasony** [comment]
Thanks for the report, and sorry for the long delay.

**Root cause**: in v2.2.1 the plugin declared `<depends optional="true">com.intellij.database</depends>` without a `config-file`, while the `<add-to-group group-id="DatabaseViewPopupMenu">` registration lived in the main `plugin.xml`. That meant the action was registered unconditionally — even in environments where the Database Tools plugin (which owns the `DatabaseViewPopupMenu` group) isn't loaded, such as the Remote Dev backend in your setup. Hence the `PluginException: group with id "DatabaseViewPopupMenu" isn't registered`.

**Fix**: since every feature of this plugin depends on Database Tools APIs, v2.3.0 declares `com.intellij.database` as a **required** dependency instead. The plugin now only loads when Database Tools is present, so the group is always registered before our action is added. Verified with the JetBrains Plugin Verifier against IU 2026.1.4 — compatible, zero plugin configuration defects.

The fix ships with v2.3.0 (requires IDE 2024.2+). Closing this issue.
