### ISSUE TITLE
Idea plugin failure (idea 15)

### ISSUE THREAD

**Issue by krolen** [yseasony/idea-sql-generator-tool#3]
update failed for AnAction with ID=sqlGenerate: com/intellij/database/psi/DbTableElement
java.lang.NoClassDefFoundError: com/intellij/database/psi/DbTableElement
    at org.yseasony.sqlgenerator.SqlGeneratorAction.update(SqlGeneratorAction.java:38)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:114)
    at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
    at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:95)
    at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:70)
    at com.intellij.ui.PopupHandler.mouseReleased(PopupHandler.java:55)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
    at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.database.psi.DbTableElement PluginClassLoader[org.yseasony.sqlgenerator, 1.2]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 47 more

**Comment by yseasony** [comment]
@krolen IDE version is 15?

**Comment by krolen** [comment]
idea 15, the latest one (see subj)

**Comment by kamronbatman** [comment]
Same error.

**Comment by yseasony** [comment]
idea 15 change a lot of openapi。 T_T

**Comment by ms502040** [comment]
same error in phpstorm 10.0.3

**Comment by edisonX-sudo** [comment]
and IDEA16 cannot find com.intellij.database.util.DasUtil T_T

**Comment by holysky5** [comment]
I have a fatal error of "NoClassDefFoundError: update failed for AnAction with ID=sqlGenerate: com/intellij/database/psi/DbTableElement"

**Comment by arhalexandre** [comment]
Same error.
update failed for AnAction with ID=sqlGenerate: com/intellij/database/psi/DbTableElement

**Comment by yseasony** [comment]
please  update. it’s fix now
